const FALLBACK_PRODUCTS = [
  {
    id: 'biotech-liposomal-anti-fungal-soap',
    name: 'Liposomal Anti-Fungal Soap',
    subtitle: 'LIPOSOMAL ANTI-FUNGAL SOAP',
    price: 14.99,
    image: '/images/Anti-Fungal Soap.png',
    description: 'Advanced, clinically inspired liposomal bar soap engineered to target fungal-prone skin with continuous, gentle active delivery.',
    details: ['Sulfur (10%)','Salicylic Acid (3%)','Liposomal actives for prolonged contact','Dermatologically guided cleansing'],
    volume: '75GM',
    category: 'Soaps',
    rating: 4.8,
    reviewsCount: 520,
    stock: 25,
    texture: 'Bar',
    fragranceProfile: 'Medicinal',
    ingredients: ['Sulfur','Salicylic Acid'],
    careGoals: ['Anti-fungal','Acne-support'],
    label: 'NEW'
  },
  {
    id: 'biotech-liposomal-l-glutathione-soap',
    name: 'Liposomal L-Glutathione Soap',
    subtitle: 'LIPOSOMAL L-GLUTATHIONE SOAP',
    price: 14.99,
    image: '/images/Glutathione Soap.png',
    description: 'Scientific brightening bar soap formulated with liposomal glutathione and supportive antioxidants for visibly refined, even-toned skin.',
    details: ['Glutathione','Vitamin C & E','Kojic Acid','Niacinamide'],
    volume: '75GM',
    category: 'Soaps',
    rating: 4.7,
    reviewsCount: 410,
    stock: 22,
    texture: 'Bar',
    fragranceProfile: 'Fresh',
    ingredients: ['Glutathione','Vitamin C','Vitamin E','Kojic Acid','Niacinamide'],
    careGoals: ['Brightening','Exfoliation'],
    label: 'NEW'
  },
  {
    id: 'biotech-anti-hair-fall-shampoo',
    name: 'Liposomal Anti-Hair Fall Hair Nourishment Medicated Shampoo',
    subtitle: 'LIPOSOMAL ANTI-HAIR FALL SHAMPOO',
    price: 19.99,
    image: '/images/Anti-Hair Fall Shampoo.png',
    description: 'Medicated shampoo delivering supportive liposomal actives for hair strength—engineered to reduce the look of shedding and nourish the scalp.',
    details: ['Biotin','Keratin','Salicylic Acid','Vitamin B6','Vitamin E'],
    volume: '200ml',
    category: 'Hair Care',
    rating: 4.6,
    reviewsCount: 180,
    stock: 18,
    texture: 'Shampoo',
    fragranceProfile: 'Herbal',
    ingredients: ['Biotin','Keratin','Salicylic Acid','Vitamin B6','Vitamin E'],
    careGoals: ['Anti-hair fall','Nourishment'],
    label: 'NEW'
  },
  {
    id: 'biotech-anti-acne-facewash',
    name: 'Liposomal Anti-Acne Medicated Facewash',
    subtitle: 'LIPOSOMAL ANTI-ACNE FACEWASH',
    price: 18.99,
    image: '/images/Anti-Acne Facewash.png',
    description: 'Clinical liposomal medicated facewash designed for clearer-looking skin—supports acne management with layered, continuous active release.',
    details: ['Salicylic Acid','A.C Net Gel','Sodium Hyaluronate','Vitamin B3','Collagen'],
    volume: '150ml',
    category: 'Facewash',
    rating: 4.7,
    reviewsCount: 260,
    stock: 20,
    texture: 'Gel',
    fragranceProfile: 'Clean',
    ingredients: ['Salicylic Acid','A.C Net Gel','Sodium Hyaluronate','Vitamin B3','Collagen'],
    careGoals: ['Anti-acne','Hydration'],
    label: 'NEW'
  },
  {
    id: 'biotech-brightening-facewash',
    name: 'Liposomal Medicated Brightening Facewash',
    subtitle: 'LIPOSOMAL MEDICATED BRIGHTENING FACEWASH',
    price: 18.99,
    image: '/images/Medicated Brightening Facewash.png',
    description: 'Brightening liposomal facewash formulated with multifunctional botanicals and antioxidants to support a more even, luminous complexion.',
    details: ['Alpha Arbutin','Beta Arbutin','Hyaluronic Acid','Glutathione','Vitamin C','Aloe Vera','L-Arginine'],
    volume: '150ml',
    category: 'Facewash',
    rating: 4.8,
    reviewsCount: 310,
    stock: 24,
    texture: 'Gel',
    fragranceProfile: 'Fresh',
    ingredients: ['Alpha Arbutin','Beta Arbutin','Hyaluronic Acid','Glutathione','Vitamin C','Aloe Vera','L-Arginine'],
    careGoals: ['Brightening','Exfoliation'],
    label: 'NEW'
  },
  {
    id: 'biotech-skinosome',
    name: 'Skinosome',
    subtitle: 'DARK SPOT TREATMENT SKINOSOME',
    price: 24.99,
    image: '/images/Skinosome Cream Tube.png',
    description: 'Dark spot treatment cream engineered to support targeted pigment reduction while improving comfort and visibly refined skin texture.',
    details: ['Vitamin E','Vitamin C','Alpha Arbutin','Licorice Extract','Allantoin'],
    volume: '30gms',
    category: 'Skincare (Creams & Serums)',
    rating: 4.6,
    reviewsCount: 210,
    stock: 16,
    texture: 'Cream',
    fragranceProfile: 'Soft',
    ingredients: ['Vitamin E','Vitamin C','Alpha Arbutin','Licorice Extract','Allantoin'],
    careGoals: ['Dark spots','Even tone'],
    label: 'NEW'
  },
  {
    id: 'biotech-liposomal-brightening-cream',
    name: 'Liposomal Brightening Cream',
    subtitle: 'LIPOSOMAL BRIGHTENING CREAM',
    price: 26.99,
    image: '/images/Liposomal Brightening Cream.png',
    description: 'Liposomal brightening cream designed for antioxidant support and hydration—helps deliver a visibly smoother, more luminous complexion.',
    details: ['Glutathione','Arbutin','Vit. C','Hyaluronic Acid'],
    volume: '50ml',
    category: 'Skincare (Creams & Serums)',
    rating: 4.7,
    reviewsCount: 240,
    stock: 18,
    texture: 'Cream',
    fragranceProfile: 'Neutral',
    ingredients: ['Glutathione','Arbutin','Vitamin C','Hyaluronic Acid'],
    careGoals: ['Brightening','Hydration'],
    label: 'NEW'
  },
  {
    id: 'biotech-liposomal-acne-repair-complex',
    name: 'Liposomal Acne Repair Complex',
    subtitle: 'LIPOSOMAL ACNE REPAIR COMPLEX',
    price: 21.99,
    image: '/images/Acne Repair Complex Serum (dropper).png',
    description: 'Targeted acne repair serum powered by dermatology-forward actives—supports clearer appearance while calming the look of stressed skin.',
    details: ['Azelaic Acid Gel','Salicylic Acid','Madecassoside'],
    volume: '30ml',
    category: 'Skincare (Creams & Serums)',
    rating: 4.6,
    reviewsCount: 195,
    stock: 19,
    texture: 'Gel-Serum',
    fragranceProfile: 'Clean',
    ingredients: ['Azelaic Acid','Salicylic Acid','Madecassoside'],
    careGoals: ['Acne repair','Soothing'],
    label: 'NEW'
  },
  {
    id: 'biotech-hyasomal-complete-repair-complex',
    name: 'Hyasomal Complete Repair Complex',
    subtitle: 'HYASOMAL COMPLETE REPAIR COMPLEX',
    price: 23.99,
    image: '/images/Hyasomal Complete Repair Complex Serum.png',
    description: 'Hyasomal repair complex engineered to support barrier recovery, wrinkle comfort, and hydrated plumpness for resilient-looking skin.',
    details: ['DMAE','Matrixyl 3000','MAP Vit C Derivative','Hyaluronic Acid LMW','Niacinamide'],
    volume: '30ml',
    category: 'Skincare (Creams & Serums)',
    rating: 4.8,
    reviewsCount: 230,
    stock: 17,
    texture: 'Serum',
    fragranceProfile: 'Fragrance-free',
    ingredients: ['DMAE','Matrixyl 3000','Vitamin C Derivative','Hyaluronic Acid','Niacinamide'],
    careGoals: ['Repair','Hydration'],
    label: 'NEW'
  },
  {
    id: 'biotech-liposomal-glutathione-500mg',
    name: 'Liposomal L-Glutathione 500mg',
    subtitle: 'LIPOSOMAL L-GLUTATHIONE 500MG',
    price: 29.99,
    image: '/images/L-Glutathione 500mg Supplement.png',
    description: 'Liposomal glutathione supplement engineered for higher bioavailability support alongside antioxidant co-actives.',
    details: ['+ Alpha Lipoic Acid','Vitamin C & E','Liposomal delivery system'],
    volume: '30 Capsules',
    category: 'Oral Supplements',
    rating: 4.7,
    reviewsCount: 120,
    stock: 25,
    texture: 'Capsules',
    fragranceProfile: '—',
    ingredients: ['Glutathione','Alpha Lipoic Acid','Vitamin C','Vitamin E'],
    careGoals: ['Antioxidant support'],
    label: 'NEW'
  },
  {
    id: 'biotech-hyasomal-sodium-hyaluronate-200mg',
    name: 'Hyasomal — Sodium Hyaluronate 200mg',
    subtitle: 'HYASOMAL SODIUM HYALURONATE 200MG',
    price: 27.99,
    image: '/images/Hyasomal Boxes.png',
    description: 'Hyasomal sodium hyaluronate supplement engineered for hydration support—designed for daily wellness routines.',
    details: ['Hyasomal delivery','Daily hydration support','Dermal-plump comfort focus'],
    volume: '30 Capsules',
    category: 'Oral Supplements',
    rating: 4.6,
    reviewsCount: 105,
    stock: 22,
    texture: 'Capsules',
    fragranceProfile: '—',
    ingredients: ['Sodium Hyaluronate'],
    careGoals: ['Hydration support'],
    label: 'NEW'
  }
];

const buildFallbackCategories = (products = FALLBACK_PRODUCTS) => {
  const grouped = products.reduce((accumulator, product) => {
    const categoryName = product.category || 'Uncategorized';
    if (!accumulator[categoryName]) {
      accumulator[categoryName] = { name: categoryName, count: 0 };
    }
    accumulator[categoryName].count += 1;
    return accumulator;
  }, {});
  return Object.values(grouped).sort((left, right) => left.name.localeCompare(right.name));
};

const createFallbackStore = () => ({
  products: FALLBACK_PRODUCTS,
  categories: buildFallbackCategories(FALLBACK_PRODUCTS),
  orders: [],
  messages: []
});

export { FALLBACK_PRODUCTS, buildFallbackCategories, createFallbackStore };
